channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=1_llvm
- afterimage=1.21=h37b8349_1003
- amqp=2.5.2=py_0
- astroid=1.6.5=py37_0
- astroplan=0.5=py37_0
- astropy-healpix=0.5=py37hc1659b7_0
- astropy=4.0=py37h8f50634_2
- attrs=19.3.0=py_0
- autoconf=2.69=pl526h14c3975_9
- automake=1.16.1=pl526_1003
- automat=20.2.0=py_0
- bayeswave=1.0.5=hb6c7934_3
- bayeswaveutils=1.0.5=py37hc8dfbb8_3
- bc=1.07.1=h516909a_0
- bcrypt=3.1.7=py37h8f50634_1
- beautifulsoup4=4.8.1=py37_0
- bilby=0.6.1=py_0
- bilby_pipe=0.3.5=py_0
- billiard=3.6.3.0=py37h516909a_0
- binutils-meta=1.0.4=0
- binutils_impl_linux-64=2.34=h53a641e_2
- binutils_linux-64=2.34=hc952b39_18
- blas=2.16=openblas
- bleach=3.1.5=pyh9f0ad1d_0
- blosc=1.18.1=he1b5a44_0
- boost-cpp=1.70.0=h8e57a91_2
- boost=1.70.0=py37h9de70de_1
- boto=2.49.0=py_0
- bottle=0.12.17=py_0
- bruco=0.1.2=py37_0
- bzip2=1.0.8=h516909a_2
- c-compiler=1.0.4=h516909a_0
- ca-certificates=2020.4.5.1=hecc5488_0
- cairo=1.16.0=hcf35c78_1003
- celery-eternal=0.1.1=py_0
- celery-singleton=0.1.3=py_1
- celery=4.3.0=py_1
- certifi=2019.9.11=py37_0
- cffi=1.14.0=py37hd463f26_0
- cfitsio=3.470=hb60a0a2_2
- chardet=3.0.4=py37hc8dfbb8_1006
- chealpix=3.31.0=h60f8253_0
- click-didyoumean=0.0.3=pyh8c360ce_0
- click=7.0=py_0
- cloudpickle=1.4.1=py_0
- cmake=3.15.5=hf94ab9c_0
- colorama=0.4.3=py_0
- coloredlogs=14.0=py37hc8dfbb8_1
- comet=3.1.0=py_0
- compilers=1.0.4=0
- configargparse=1.2.3=pyh9f0ad1d_0
- configobj=5.0.6=py_0
- constantly=15.1.0=py_0
- coreutils=8.31=h516909a_0
- corner=2.0.1=py_1003
- cryptography=2.8=py37hb09aad4_2
- curl=7.65.3=hf8cf82a_0
- cursor=1.3.4=pyh8c360ce_0
- cwinpy=0.2.1=py_0
- cxx-compiler=1.0.4=hc9558a2_0
- cycler=0.10.0=py_2
- cyrus-sasl=2.1.27=he38ecfd_0
- cython=0.29.14=py37he1b5a44_0
- davix=0.7.5=hb54d6fb_1
- dbus-python=1.2.16=py37h1369247_0
- dbus=1.13.6=he372182_0
- decorator=4.4.2=py_0
- deepdish=0.3.4=py_3
- defusedxml=0.6.0=py_0
- dill=0.3.1.1=py37hc8dfbb8_1
- dnspython=1.16.0=py_1
- dqsegdb2=1.0.1=py_0
- dqsegdb=1.6.1=py37_0
- dynesty=1.0.1=py_1
- ecdsa=0.13=py_0
- emcee=2.2.1=pyh24bf2e0_4
- entrypoints=0.3=py37hc8dfbb8_1001
- expat=2.2.9=he1b5a44_2
- fftw=3.3.8=nompi_h7f3a6c3_1110
- flake8=3.7.9=py37hc8dfbb8_1
- flask-cache=0.13.1=py_1000
- flask-sqlalchemy=2.4.0=py_0
- flask=0.12.4=py_0
- flex=2.6.4=he1b5a44_1004
- fontconfig=2.13.1=h86ecdb6_1001
- fortran-compiler=1.0.4=he991be0_0
- freetype=2.10.1=he06d7ca_0
- fribidi=1.0.9=h516909a_0
- future=0.18.2=py37hc8dfbb8_1
- gcc_impl_linux-64=7.3.0=hd420e75_5
- gcc_linux-64=7.3.0=h553295d_18
- gct=6.2.1550507116=he9ae1f9_1
- gdk-pixbuf=2.38.2=h3f25603_3
- geos=3.7.2=he1b5a44_2
- gettext=0.19.8.1=hc5be6a0_1002
- gfortran_impl_linux-64=7.3.0=hdf63c60_5
- gfortran_linux-64=7.3.0=h553295d_18
- giflib=5.2.1=h516909a_2
- git-lfs=2.9.0=0
- git=2.23.0=pl526hce37bd2_2
- gitdb2=4.0.2=py_0
- gitdb=4.0.5=py_0
- gitpython=2.1.11=py_0
- glew=2.0.0=he1b5a44_1003
- glib=2.58.3=py37he00f558_1004
- gmp=6.2.0=he1b5a44_2
- gobject-introspection=1.56.1=py37h2da5eee_1002
- gpstime=0.3.3=py_0
- gracedb-sdk=0.1.6=py_0
- graphite2=1.3.13=he1b5a44_1001
- graphviz=2.42.3=h0511662_0
- gsl=2.6=h294904e_0
- gst-orc=0.4.31=h516909a_0
- gst-plugins-base=1.14.4=h0935bb2_1002
- gst-plugins-good=1.14.4=h08bb679_1002
- gst-python=1.14.4=py37h6379271_1
- gstreamer=1.14.4=h36ae1b5_1002
- gwdatafind=1.0.4=py_0
- gwdetchar=1.0.0=py37_0
- gwollum=2.3.12=h1afb2d1_1
- gwosc=0.5.3=py_0
- gwpy=1.0.1=py37_0
- gwsumm=1.0.0=py37_1
- gwsurrogate=1.0.1=py37ha777a67_1
- gwtools=1.0.4=py_0
- gwtrigfind=0.8.0=py_0
- gxx_impl_linux-64=7.3.0=hdf63c60_5
- gxx_linux-64=7.3.0=h553295d_18
- h5py=2.10.0=nompi_py37h513d04c_102
- halo=0.0.28=py_0
- harfbuzz=2.4.0=h9f30f68_3
- hdf5=1.10.5=nompi_h3c11f04_1104
- healpy=1.13.0=py37hf476568_1
- htchirp=1.0=py_0
- htcondor-classads=8.9.5=he1b5a44_2
- htcondor-procd=8.9.5=he1b5a44_2
- htcondor-utils=8.9.5=hf10cc52_2
- htcondor=8.9.5=py37_2
- htmap=0.5.0=py_0
- humanfriendly=8.2=py37hc8dfbb8_0
- humanize=0.5.1=py_1
- hveto=1.0.1=py37_1
- hyperlink=19.0.0=pyh9f0ad1d_0
- icu=64.2=he1b5a44_1
- idna=2.8=py37_1000
- idq=0.3.1=py37_0
- importlib-metadata=1.6.0=py37hc8dfbb8_0
- importlib_metadata=1.6.0=0
- incremental=17.5.0=py_0
- ipykernel=4.10.0=py37_0
- ipyparallel=6.3.0=py37hc8dfbb8_0
- ipython=5.8.0=py37_1
- ipython_genutils=0.2.0=py_1
- isort=4.3.21=py37hc8dfbb8_1
- itsdangerous=1.1.0=py_0
- jinja2=2.10.3=py_0
- jpeg=9c=h14c3975_1001
- jsonschema=3.2.0=py37hc8dfbb8_1
- jupyter_client=5.3.3=py37_1
- jupyter_console=5.2.0=py37_1
- jupyter_core=4.6.1=py37_0
- kiwisolver=1.2.0=py37h99015e2_0
- kombine=0.8.4=py_0
- kombu=4.6.8=py37hc8dfbb8_1
- krb5=1.16.4=h2fd8d38_0
- lal=6.22.0=fftw_h9392de7_101
- lalapps=6.25.1=py37h7e6a3ff_3
- lalburst=1.5.4=h7495f13_3
- lalframe=1.5.0=h516909a_2
- lalinference=2.0.0=h2f7d59f_0
- lalinspiral=1.10.0=h7495f13_3
- lalmetaio=1.6.0=h516909a_2
- lalpulsar=1.18.2=h1249155_2
- lalsimulation=2.0.0=h7495f13_0
- lalsuite=6.70=pyh9f0ad1d_0
- lazy-object-proxy=1.4.3=py37h8f50634_2
- ld_impl_linux-64=2.34=h53a641e_2
- ldas-tools-al=2.6.4=hfd22054_0
- ldas-tools-diskcacheapi-swig=2.6.8=hc9558a2_0
- ldas-tools-diskcacheapi=2.7.0=h8b68381_0
- ldas-tools-filters=2.6.4=hc9558a2_0
- ldas-tools-frameapi-swig=2.6.8=hc9558a2_0
- ldas-tools-frameapi=2.6.4=he9ae1f9_0
- ldas-tools-framecpp-swig=2.6.9=he1b5a44_1
- ldas-tools-framecpp=2.7.0=hc509bcd_1
- ldas-tools-ldasgen-swig=2.6.7=hc9558a2_0
- ldas-tools-ldasgen=2.7.0=h11112f5_1
- libblas=3.8.0=16_openblas
- libcblas=3.8.0=16_openblas
- libclang=9.0.1=default_hde54327_0
- libcondor_utils=8.9.5=h0636c6a_2
- libcroco=0.6.13=h8d621e5_1
- libcurl=7.65.3=hda55be3_0
- libcxx=9.0.1=2
- libcxxabi=9.0.1=2
- libdaemon=0.14=h516909a_0
- libedit=3.1.20170329=hf8c457e_1001
- libffi=3.2.1=he1b5a44_1007
- libframe=8.30=h14c3975_1000
- libgcc-ng=9.2.0=h24d8f2e_2
- libgcrypt=1.8.4=hf484d3e_1000
- libgfortran-ng=7.3.0=hdf63c60_5
- libglu=9.0.0=he1b5a44_1001
- libgomp=9.2.0=h24d8f2e_2
- libgpg-error=1.36=he1b5a44_0
- libgsasl=1.8.0=h19a2143_1004
- libiconv=1.15=h516909a_1006
- libidn2=2.3.0=h516909a_0
- liblapack=3.8.0=16_openblas
- liblapacke=3.8.0=16_openblas
- libllvm8=8.0.1=hc9558a2_0
- libllvm9=9.0.1=he513fc3_1
- libntlm=1.4=h516909a_1002
- libopenblas=0.3.9=h5ec1e0e_0
- libpng=1.6.37=hed695b0_1
- libpq=12.2=hae5116b_0
- librdkafka=0.11.5=hb2b7465_1003
- librsvg=2.48.4=h33a7fed_0
- libsodium=1.0.17=h516909a_0
- libssh2=1.8.2=h22169c7_2
- libstdcxx-ng=9.2.0=hdf63c60_2
- libtiff=4.1.0=hc7e4089_6
- libtool=2.4.6=h14c3975_1002
- libunistring=0.9.10=h14c3975_0
- libuuid=2.32.1=h14c3975_1000
- libuv=1.34.0=h516909a_0
- libwebp-base=1.1.0=h516909a_3
- libxcb=1.13=h14c3975_1002
- libxkbcommon=0.10.0=he1b5a44_0
- libxml2=2.9.10=hee79883_0
- libxslt=1.1.33=h31b3aaa_0
- ligo-common=1.0.4=py_0
- ligo-followup-advocate=1.1.7=py_0
- ligo-gracedb=2.5.0=py_0
- ligo-lvalert=1.5.6=py37_0
- ligo-raven=1.17=py37_0
- ligo-scald=0.7.2=py_0
- ligo-segments=1.2.0=py37h516909a_2
- ligo.skymap=0.1.16=py37h5b7492b_0
- ligotimegps=2.0.0=py_0
- lintegrate=0.1.3=py37h586b295_2
- llvm-openmp=10.0.0=hc9558a2_0
- llvmlite=0.31.0=py37h5202443_1
- log_symbols=0.0.14=pyh8c360ce_0
- lscsoft-glue=2.0.0=py37h516909a_1
- lxml=4.4.2=py37h7ec2d77_0
- lz4-c=1.8.3=he1b5a44_1001
- lzo=2.10=h14c3975_1000
- m2crypto=0.35.2=py37h72c5cf5_0
- m4=1.4.18=h14c3975_1001
- mako=1.1.0=py_0
- markdown=3.2.1=py_0
- markuppy=1.14=py_0
- markupsafe=1.1.1=py37h8f50634_1
- matplotlib-base=3.1.2=py37h250f245_1
- matplotlib=3.1.2=py37_1
- mccabe=0.6.1=py_1
- metaio=8.5.1=h84994c4_1000
- metakernel=0.24.4=pyh9f0ad1d_0
- mistune=0.8.4=py37h8f50634_1001
- mkl=2019.5=281
- mock=4.0.2=py37hc8dfbb8_0
- more-itertools=8.2.0=py_0
- mpi=1.0=openmpi
- mpld3=0.3=py_2
- munge=0.5.13=h1a52d62_0
- nbconvert=5.6.1=py37hc8dfbb8_1
- nbformat=4.4.0=py_1
- ncurses=6.1=hf484d3e_1002
- nds2-client=0.16.5=hd02d5f2_0
- networkx=2.4=py_1
- notebook=5.7.8=py37_1
- nspr=4.25=he1b5a44_0
- nss=3.47=he751ad9_0
- numba=0.47.0=py37hb3f55d8_0
- numexpr=2.7.1=py37h0da4684_1
- numpy=1.16.5=py37h95a1406_0
- olefile=0.46=py_0
- omicron=2.3.12=h13505ea_0
- openmpi=4.0.2=hdf1f1ad_4
- openssl=1.1.1f=h516909a_0
- p_astro=0.8.1=py_0
- packaging=20.1=py_0
- pamela=1.0.0=py_0
- pandas=0.24.2=py37hb3f55d8_1
- pandoc=2.7.3=0
- pandocfilters=1.4.2=py_1
- pango=1.42.4=h7062337_4
- patsy=0.5.1=py_0
- pcre=8.44=he1b5a44_0
- pepredicates=0.0.3=py_0
- perl=5.26.2=h516909a_1006
- pesummary=0.5.3=py_0
- pexpect=4.8.0=py37hc8dfbb8_1
- pickleshare=0.7.5=py37hc8dfbb8_1001
- pillow=7.1.2=py37h718be6c_0
- pip=19.3.1=py37_0
- pixman=0.38.0=h516909a_1003
- pkg-config=0.29.2=h516909a_1006
- plotly=4.7.1=pyh9f0ad1d_0
- pluggy=0.13.1=py37hc8dfbb8_1
- portalocker=1.7.0=py37hc8dfbb8_0
- prometheus_client=0.7.1=py_0
- prompt_toolkit=1.0.15=py_1
- psycopg2=2.8.4=py37h72c5cf5_1
- ptemcee=1.0.0=py_0
- pthread-stubs=0.4=h14c3975_1001
- ptyprocess=0.6.0=py_1001
- py=1.8.0=py_0
- pyasn1-modules=0.2.7=py_0
- pyasn1=0.4.8=py_0
- pycairo=1.19.1=py37h01af8b0_3
- pycbc=1.15.4=py37hef5361f_0
- pycodestyle=2.5.0=py_0
- pycondor=0.5.0=py_1
- pycparser=2.20=py_0
- pycryptodome=3.9.7=py37hb05bdb2_1
- pyflakes=2.1.1=py_0
- pygcn=1.0.2=py_0
- pygments=2.4.2=py_0
- pygobject=3.30.5=py37hfc86313_1
- pyhamcrest=2.0.2=py_0
- pykerberos=1.2.1=py37h89bfc95_1
- pylint=1.9.2=py37_0
- pyopenssl=19.0.0=py37_0
- pyparsing=2.4.7=pyh9f0ad1d_0
- pyqt=5.12.3=py37h8685d9f_3
- pyrsistent=0.16.0=py37h8f50634_0
- pyrxp=2.1.0=py37h516909a_1000
- pysocks=1.7.1=py37hc8dfbb8_1
- pytables=3.5.2=py37h9f153d1_2
- pytest-runner=5.2=py_0
- pytest-socket=0.3.3=py_0
- pytest=5.3.5=py37hc8dfbb8_2
- pythia8=8.244=py37h3340039_0
- python-avahi=0.7=py37hb996a4a_0
- python-confluent-kafka=0.11.4=py37hba13f1d_1002
- python-dateutil=2.8.1=py_0
- python-htcondor=8.9.5=py37hf4ca894_2
- python-lal=6.22.0=fftw_py37h89c1f2d_101
- python-lalburst=1.5.4=py37h03ebfcd_3
- python-lalframe=1.5.0=py37h03ebfcd_2
- python-lalinference=2.0.0=py37h03ebfcd_0
- python-lalinspiral=1.10.0=py37h03ebfcd_3
- python-lalmetaio=1.6.0=py37h03ebfcd_2
- python-lalpulsar=1.18.2=py37h586b295_2
- python-lalsimulation=2.0.0=py37h03ebfcd_0
- python-ldas-tools-al=2.6.7=py37hc9558a2_1
- python-ldas-tools-diskcacheapi=2.6.8=py37hc9558a2_0
- python-ldas-tools-frameapi=2.6.8=py37hc9558a2_0
- python-ldas-tools-framecpp=2.6.9=py37hb3f55d8_0
- python-ldas-tools-ldasgen=2.6.7=py37hc9558a2_0
- python-ligo-lw=1.5.3=py37h14c3975_0
- python-nds2-client=0.16.7=py37h0da4684_0
- python-pegasus-wms=4.9.2=py_0
- python=3.7.6=h8356626_5_cpython
- python_abi=3.7=1_cp37m
- pytz=2019.3=py_0
- pyyaml=5.1.2=py37h516909a_0
- pyzmq=19.0.1=py37hac76be4_0
- qt=5.12.5=hd8c4c69_1
- readline=8.0=hf8c457e_0
- redis-py=3.3.11=py_0
- reproject=0.7=py37h03ebfcd_0
- requests-ecp=0.2.1=py_0
- requests-gracedb=0.1.3=py_0
- requests-kerberos=0.12.0=py37_0
- requests-mock=1.7.0=py_0
- requests=2.22.0=py37_1
- retrying=1.3.3=py_2
- rhash=1.3.6=h14c3975_1001
- rift=0.0.15.1=py37_0
- root-binaries=6.18.04=py37hc9266a3_28
- root-dependencies=6.18.04=py37hc9266a3_28
- root=6.18.04=py37hc9266a3_28
- root_base=6.18.04=py37he8dbe36_28
- safe-netrc=1.0.0=py_0
- scikit-learn=0.19.2=py37h22eb022_0
- scipy=1.4.1=py37ha3d9a3c_3
- seaborn=0.9.0=py_2
- send2trash=1.5.0=py_0
- sentry-sdk=0.13.2=py_0
- service_identity=18.1.0=py_0
- setuptools=41.6.0=py37_1
- shapely=1.6.4=py37hec07ddf_1006
- simplegeneric=0.8.1=py_1
- six=1.13.0=py37_0
- sleekxmpp=1.3.3=py_0
- smmap=3.0.4=pyh9f0ad1d_0
- soupsieve=1.9.4=py37hc8dfbb8_1
- spinners=0.0.23=pyh8c360ce_0
- sqlalchemy=1.3.11=py37h516909a_0
- sqlite=3.30.1=hcee41ef_0
- statsmodels=0.11.1=py37h8f50634_1
- swig=3.0.12=hf484d3e_1003
- tbb-devel=2020.1=hc9558a2_0
- tbb=2020.1=hc9558a2_0
- termcolor=1.1.0=py_2
- terminado=0.8.3=py37hc8dfbb8_1
- testpath=0.4.4=py_0
- tk=8.6.10=hed695b0_0
- toml=0.10.0=py_0
- tornado=6.0.4=py37h8f50634_1
- tqdm=4.38.0=py_2
- traitlets=4.3.3=py37hc8dfbb8_1
- twisted=19.10.0=py37h516909a_0
- urllib3=1.25.7=py37hc8dfbb8_1
- vdt=0.4.3=he1b5a44_0
- vine=1.3.0=py_0
- virtualenv=16.7.5=py_0
- voeventlib=1.2=py_0
- voms=2.1.0rc0=h2c113ba_1
- wcwidth=0.1.9=pyh9f0ad1d_0
- webencodings=0.5.1=py_1
- werkzeug=0.16.0=py_0
- wget=1.20.1=h22169c7_0
- wheel=0.33.6=py37_0
- wrapt=1.12.1=py37h8f50634_1
- xorg-fixesproto=5.0=h14c3975_1002
- xorg-kbproto=1.0.7=h14c3975_1002
- xorg-libice=1.0.10=h516909a_0
- xorg-libsm=1.2.3=h84519dc_1000
- xorg-libx11=1.6.9=h516909a_0
- xorg-libxau=1.0.9=h14c3975_0
- xorg-libxcursor=1.2.0=h516909a_0
- xorg-libxdmcp=1.1.3=h516909a_0
- xorg-libxext=1.3.4=h516909a_0
- xorg-libxfixes=5.0.3=h516909a_1004
- xorg-libxft=2.3.3=h71203ad_0
- xorg-libxpm=3.5.13=h516909a_0
- xorg-libxrender=0.9.10=h516909a_1002
- xorg-libxt=1.1.5=h516909a_1003
- xorg-renderproto=0.11.1=h14c3975_1002
- xorg-xextproto=7.3.0=h14c3975_1002
- xorg-xproto=7.0.31=h14c3975_1007
- xrootd=4.11.3=py37h2f28ec6_1
- xz=5.2.5=h516909a_0
- yaml=0.1.7=h14c3975_1001
- zeromq=4.3.2=he1b5a44_2
- zipp=1.0.0=py_0
- zlib=1.2.11=h516909a_1006
- zope.interface=4.7.1=py37h516909a_0
- zstd=1.4.4=h3b9ef0a_2
name: igwn-py37
